# Generated by Django 3.0.3 on 2020-03-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
