# Generated by Django 3.0.4 on 2020-03-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='rarity',
            new_name='films',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trading_post.Deck'),
        ),
        migrations.AlterField(
            model_name='card',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trading_post.Species'),
        ),
    ]
