# Generated by Django 3.0.3 on 2020-03-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(to='trading_post.Card'),
        ),
    ]
