# Generated by Django 3.0.3 on 2020-03-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_post', '0002_auto_20200317_1700'),
        ('trading_post', '0002_auto_20200317_2005'),
    ]

    operations = [
    ]
