# Generated by Django 3.0.4 on 2020-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='accounts/pictures/st_404.jpg', null=True, upload_to='accounts/pictures'),
        ),
    ]
